### ISSUE TITLE
text-only mode for post window

### ISSUE THREAD

**Issue by htor** [crucialfelix/atom-supercollider#103]
the output from sclang is currently parsed and displayed in a custom format in the post window, instead of the raw text output. this is useful in many cases, but it think it would be useful to provide an option to toggle between this mode and a raw text output mode (like in the SC-IDE) under the plugin preferences. the raw text mode would just pipe the output directly into the post window, without any parsing or formatting.
i can attempt to make a pr with this feature, if you agree this is useful.

and i just want to say thanks for creating this project and `supercolliderjs`. these are great packages to have in the js ecosystem!

**Comment by crucialfelix** [comment]
Do you want that for copy and paste? Because I think there is atom support
for what the copy buffer gets. Afair I did implement simple text when you
copy.

Thanks and glad you are enjoying it!

Herman Torjussen <notifications@github.com> schrieb am Sa., 24. Aug. 2019,
09:36:

**Comment by htor** [comment]
i see! i wasn't thinking specially about copy+pasting, i just wanted to have the same type of output like in the sc-ide and other supercollider environments. i think many are used to "parsing" the raw output themselves (and prefer not having smart stack trace parsing) and would maybe experience less friction when switching from other environments (sc-ide, scvim) to this package. in this text-only mode the post window could in theory just be another text scrollable, non-editable text buffer. what do you think?

**Comment by htor** [comment]
closing. not a feature i care about anymore. cheers!
