### ISSUE TITLE
No Microphone/Audio in on MacOS (solved)

### ISSUE THREAD

**Issue by mhairston** [crucialfelix/atom-supercollider#110]
Posting this issue with solution in case someone finds it helpful:

PROBLEM

I've been using Atom exclusively to run SuperCollider for years now, and for the last few months I've been banging my head on a wall trying to process incoming audio: nothing would show up at the inputs. I tried different audio interfaces, aggregate devices, etc., all to no avail. I could record from the microphone in Audacity and Amadeus with no problem. I started to think it was a SC or Mac version issue.

SOLUTION

Last night I had a forehead-smacking moment: it turns out you need to give Atom permissions to use the Microphone -- go to System Preferences > Privacy > Microphone and add Atom to the list.

It may be that at some point Atom prompted me to give it mic permissions, but in the context I must have thought that didn't make sense, it's a text editor, and declined.

I assume this would be the case with other IDE alternatives like Sublime Text or VS Code.

**Comment by crucialfelix** [comment]
Posting a solution is great. The googles can find things like this even for different unrelated projects.

Also glad to hear somebody is still using atom-supercollider!

**Comment by tedthetrumpet** [comment]
Even though this is closed and solved, I thought I'd add a 2022 update!

On macOS Monterey, it seems that Atom does not ask for microphone permissions, so you can't add it in system preferences. The workaround is to do 'show packaged contents' on Atom, and then use the 'Atom' executable in the 'MacOS' folder to launch Atom in Terminal. That way Terminal asks for the microphone permissions and you get audio into SuperCollider.

**Comment by crucialfelix** [comment]
You never know, that may be good advice for someone!  Or the ML will pick it up and form a latent model of everything that went wrong in the early 21st century civilization.
