### ISSUE TITLE
ctags: automatically query based on classpath given in yaml comfig file

### ISSUE THREAD

**Issue by LFSaw** [crucialfelix/atom-supercollider#26]
or to just query sclang and export a map of methods and classes
and/or offer a command that symlinks SCClassLibrary and Extensions for you
i'd much appreciate that.

this is based on comments by @crucialfelix in #24

**Comment by crucialfelix** [comment]
New solution: adds all included paths to project. That way you can see the code you are using and it is all included by ctags indexing
