### ISSUE TITLE
CoreText performance note: Client called CTFontCreateWithName() using name "Arial" and got font with PostScript name "ArialMT". For best performance, only use PostScript names when calling this API.

### ISSUE THREAD

**Issue by ImustnotfeaR** [crucialfelix/atom-supercollider#27]
Hi hi, i get this error in the post window every time i compile some code / boot the server. I am on Mavericks 10.9 & has just installed the SC package (new usre :dancer: ). Is there a fix to this ?

Its a big error that makes it hard to read the other messages.

Thanks !!

**Comment by crucialfelix** [comment]
I think it might be the theme then. I don't actually specify any fonts at
all in atom-supercollider.  All the colors and fonts and so on come from
variables set in the active theme.

**Comment by crucialfelix** [comment]
any other questions feel free to ask.  also available here sometimes: https://gitter.im/crucialfelix/atom-supercollider
