### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by caseyanderson** [crucialfelix/atom-supercollider#30]
[Enter steps to reproduce below:]

1. open atom from terminal with file
2a. (method one) packages > supercollider > open post window
2b. (method two) simply shift enter on the first line in the file (which happens to be "o = ServerOptions.new;"), which results in this same error.

**Atom Version**: 0.177.0
**System**: linux 3.16.0-30-generic
**Thrown From**: [supercollider](https://github.com/crucialfelix/atom-supercollider) package, v0.3.5

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/cta/.atom/packages/supercollider/lib/rendering.coffee:306

TypeError: undefined is not a function
  at Object.cleanStdout (/home/cta/.atom/packages/supercollider/lib/rendering.coffee:306:9)
  at SCLang.<anonymous> (/home/cta/.atom/packages/supercollider/lib/repl.coffee:107:21)
  at SCLang.emit (events.js:116:17)
  at ChildProcess.<anonymous> (/home/cta/.atom/packages/supercollider/node_modules/supercolliderjs/lib/nodejs/sclang.js:376:10)
  at ChildProcess.emit (events.js:116:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:12)
  at child_process.js:1142:20
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -0:41.6 supercollider:eval (atom-text-editor.editor)
     -0:01.1 supercollider:open-post-window (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "zenburn"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.12
file-icons, v1.4.8
supercollider, v0.3.5
zenburn, v1.0.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by caseyanderson** [comment]
any suggestions as to how to fix the above symptom? i am currently not able to use supercollider with atom at all and am a bit mystified as to what is going on.

**Comment by crucialfelix** [comment]
Hi, sorry I never got any notification email for this. I wasn't ignoring it !

this was fixed here:  https://github.com/crucialfelix/atom-supercollider/commit/dcee742a306e7bb31476278ea5199312ed9154c8

Try it with the latest version 0.4.0

**Comment by caseyanderson** [comment]
will do so tonight and report back to confirm the fix. thanks!

**Comment by caseyanderson** [comment]
upgrading did resolve this specific error by way of resulting in no errors thrown, however nothing happens when i try to evaluate a line in an scd file, open the post window, or try to open a help file on some object in SC (example: Bus). any suggestions?

**Comment by crucialfelix** [comment]
right now the whole thing is broken because Atom switched to IOJS and are
using 6to5 to transpile files. this is raising a warning and it is refusing
to run the package. I'll sort it out tomorrow.

**Comment by caseyanderson** [comment]
Oh, ok. Glad its not just me. :)

If there is anything I can do to help, dont hesitate to ask (check on things, whatever)!

**Comment by crucialfelix** [comment]
Its now working again. I had to factor out some dependencies that atom's content security policy was complaining about.

**Comment by caseyanderson** [comment]
Great. Ill upgrade tonight or tomorrow and confirm that it is working. Thanks for your help and all of your work on this!

**Comment by caseyanderson** [comment]
I can confirm that everything is working now. Thanks again!
