### ISSUE TITLE
Uncaught Error: EBADF, write

### ISSUE THREAD

**Issue by 50Wliu** [crucialfelix/atom-supercollider#31]
_From @s8 on February 17, 2015 22:32_

[Enter steps to reproduce below:]

1. cmd-shift-p
2. supercollider
3. open post window

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EBADF, write

```
At fs.js:82

Error: EBADF, write
  at Error (native)

```

### Commands

```
     -0:35.5 command-palette:toggle (atom-text-editor.editor)
     -0:33.6 core:confirm (atom-text-editor.editor.mini)
     -0:33.6 tree-view:show (atom-text-editor.editor)
     -0:30.7 core:backspace (atom-text-editor.editor)
     -0:30.0 command-palette:toggle (atom-text-editor.editor)
  5x -0:26.5 core:move-down (atom-text-editor.editor.mini)
     -0:23.7 core:confirm (atom-text-editor.editor.mini)
     -0:23.7 supercollider:clear-post-window (atom-text-editor.editor)
  2x -0:22.6 core:close (atom-text-editor.editor)
     -0:12.6 application:new-file (div.markdown-preview.native-key-bindings)
     -0:11.5 core:close (atom-text-editor.editor)
     -0:08.9 application:new-file (atom-text-editor.editor)
     -0:06.0 command-palette:toggle (atom-text-editor.editor)
  4x -0:03.5 core:move-down (atom-text-editor.editor.mini)
     -0:00.6 core:confirm (atom-text-editor.editor.mini)
     -0:00.6 supercollider:open-post-window (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
supercollider, v0.3.5

# Dev
No dev packages
```

_Copied from original issue: atom/atom#5597_

**Comment by crucialfelix** [comment]
I've seen this before. I think its because the path to sclang is incorrect. It should detect that and report that this is the problem. I'll have a look, thanks !

**Comment by crucialfelix** [comment]
@s8 actually this says its a write error. that can only mean that its trying to write the config file to /tmp/

if you are still getting this with the latest version (0.4.0) then open up the dev tools (opt-cmd-i) and paste the whole stack trace. otherwise its impossible for me to see what happened.  I realize that you posted this via the red error popup.

**Comment by crucialfelix** [comment]
I'm still not sure what happened here.

Latest is 0.5.3

Have you ever experienced it again ? still ?

**Comment by crucialfelix** [comment]
Not sure this was actually a atom-supercollider error. Reopen if you have more information or see the exact same error again. thx
