### ISSUE TITLE
3.7 alpha sclang location change

### ISSUE THREAD

**Issue by mhetrick** [crucialfelix/atom-supercollider#33]
I just upgraded from OS X 3.6 to 3.7 alpha. The previous expected location for sclang is Resources/sclang, but it is now MacOS/sclang.

I saw the ability to create a .yaml to point to the different path, but I thought I would open an issue. Would it be possible to check in both locations for sclang, so that it will work out of the box with 3.6 and 3.7?

Also, thanks so much for this package! I can see this eventually replacing sc-ide for me.

**Comment by crucialfelix** [comment]
I think its best to explicitly set the path yourself using the config file. That way you can use the version you want, install multiple versions, install versions in a local relative folder etc.

When we get the homebrew recipe approved (with the 3.7 official release) then you would have sclang and scsynth on your path and you can use homebrew to quickly switch versions.

I'll leave this issue open and think about if I want to make it do a more complicated guess.

**Comment by crucialfelix** [comment]
thanks for the report. I changed the default location
