### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by bagong** [crucialfelix/atom-supercollider#40]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/exports/atom.js:48:11)
Object.<anonymous> (/Users/rainer/.atom/packages/supercollider/lib/post-window.coffee:2:1)
Object.<anonymous> (/Users/rainer/.atom/packages/supercollider/lib/post-window.coffee:102:4)
Module._compile (module.js:452:26)
Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
Module.load (module.js:347:32)
```

**Comment by crucialfelix** [comment]
ah, I missed one. fixed

**Comment by bagong** [comment]
There are 4 more left ;) Just run the package in current Atom (.204). It doesn't feel friendly to report them all individually... They are saying they will remove deprecated API's today...

**Comment by crucialfelix** [comment]
I did that and I already updated those and made a new release.

I don't understand why its not showing them to me. Probably because its installed with link (development mode) and there is some bug in deprecation cop.

**Comment by crucialfelix** [comment]
ah now its showing them to me.
