### ISSUE TITLE
Working on Windows?

### ISSUE THREAD

**Issue by bagong** [crucialfelix/atom-supercollider#43]
I am just opening an issue here for the Windows support issue in general. I have a testbuild of SC3.7 that runs with the default IDE (but where the qt-based communication between IDE and sclang is seriously hampered for the time being).

With Atom I get to this point: 
- when evaluating SC code in the editor the post window is opened
- under a heading config the path to .supercollider.yaml is displayed
- the (custom) path to sclang is displayed (but with a different path syntax than the one I used in the config - file (\ instead of /))
- the heading 'booting' is displayed but nothing happens.

If I copy the path to sclang.exe from the postwindow to a command-shell, sclang is booted successfully, so I think there is no typo in the path. There is also no empty space in the path.

I just wanted to give it a try, didn't have much hope anyways: it seems Atom-sc depends on the Readline interface to work? On Mac I get the sc3> prompt occasionally? Readline is broken on sc3.7, so even if the path to sclang worked it would probably bork later...
Maybe something for a later time...

**Comment by crucialfelix** [comment]
The latest version does more thorough checking of paths and config and doesn't get stuck in the boot stage if something goes wrong. Try it now when you get a chance.  thx

**Comment by bagong** [comment]
Have given this a try now. Currently the supercollider package (or the dependency supercollider.js) doesn't install, apparently because of a too low node version. In Windows (with Atom 1.7.1) node.js reports as version 0.10.40. this is the error:

```
> supercolliderjs@0.9.3 postinstall C:\Users\Rainer\AppData\Local\Temp\apm-install-dir-116316-4132-1xcs6k8\node_modules\supercollider\node_modules\supercolliderjs
> node -e "require('fs').stat('lib', function (e, s) { process.exit(e || !s.isDirectory() ? 1 : 0) })" || npm run build


npm WARN engine supercolliderjs@0.9.3: wanted: {"node":">=4 <5"} (current: {"node":"0.10.40","npm":"2.13.3"})
The system cannot find the path specified.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Rainer\\AppData\\Local\\atom\\app-1.7.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Rainer\\AppData\\Local\\atom\\app-1.7.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Rainer\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Rainer\\.atom\\.apmrc" "install" "C:\\Users\\Rainer\\AppData\\Local\\Temp\\d-116316-4132-fgjkfw\\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! supercolliderjs@0.9.3 postinstall: `node -e "require('fs').stat('lib', function (e, s) { process.exit(e || !s.isDirectory() ? 1 : 0) })" || npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the supercolliderjs@0.9.3 postinstall script 'node -e "require('fs').stat('lib', function (e, s) { process.exit(e || !s.isDirectory() ? 1 : 0) })" || npm run build'.
npm ERR! This is most likely a problem with the supercolliderjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e "require('fs').stat('lib', function (e, s) { process.exit(e || !s.isDirectory() ? 1 : 0) })" || npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls supercolliderjs
npm ERR! There is likely additional logging output above.
```

I haven't found documentation as to if it is possible to somehow include a Node version from the official installer, or whether this is bound to the Atom bundled Node.

**Comment by bagong** [comment]
Even after installing Node.js from the official download, and the system reporting `node -v` as 4.4.3, `apm` keeps reporting it's own version: 0.10.40...

**Comment by crucialfelix** [comment]
Apparently Electron is using 4.1.x but apm is stuck on 10.4 and so it's failing to install things because of this.

https://discuss.atom.io/t/node-version-in-atom-electron/22954
https://github.com/atom/apm/issues/328

It doesn't matter what your system nodejs is; that isn't used at all.  btw. use nvm if you are doing any node work so you can switch versions.

I will set node engine on the next supercolliderjs release to 10 -- it will probably work fine. 

But I was planning on pinning that to 4 so I can just transpile to that target and not have to transpile classes and arrow functions and let const etc.

**Comment by crucialfelix** [comment]
Somebody recently reported installing for windows and it working fine. So I think this is not a problem now.

**Comment by bagong** [comment]
Cool, I'll have a look when I'm done with other stuff ;) Thanks!!! When I return to the SC IDE from Atom I realize that we're living in the high resolution display age now ;)

**Comment by crucialfelix** [comment]
I am waiting for VS to support HoloLens. Then we can code in VR

**Comment by bagong** [comment]
Hahaha, that's what we need most now ;)
