### ISSUE TITLE
"Library is not compiled": JS-YAML: unacceptable kind of an object to dump [object Undefined]

### ISSUE THREAD

**Issue by 3nki** [crucialfelix/atom-supercollider#45]
running in OS X. i am using latest supercollider (3.7) and some files have been moved (sclang, scsynth) so i created a .supercollider.yaml preferences file and tried setting paths but no luck. i'm not quite sure what to put in the yaml file. i tried this:

sclang: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
scsynth: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/scsynth

and in post window Atom says:

config
configFile:	/Users/jeffblanding/.supercollider.yaml
sclang:	/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
booting

so it seems to only catch the sclang reference from yaml. if i try shift-return in a scd code block i get the error "Library is not compiled". same if i try cntrl-click for Evaluate Selection.

the section on Preferences for Atom only mentions sclang.

**Comment by crucialfelix** [comment]
It doesn't actually need or use the scsynth path because atom-supercollider
only uses the language.

That option is for other users of the underlying supercollider.js package
which can work directly with scsynth

Those paths you specified are already the defaults that it would have used,
so you don't need the config file at all.
It will always post the sclang that it uses when it boots up.

Something else is breaking.  Are there any compile errors posted ?  Can you
open the normal SC IDE and start up the language ?

In Atom press cmd-alt-i to open up the developer console. See if there are
any messages posted there.

shift-cmd-k is the shortcut to just compile the library.

I've recently refactored the code that parses the compile error messages
but I haven't published that new version yet.

**Comment by 3nki** [comment]
i am using the latest version (3.7alpha0), and they have moved sclang and scsynth and some other files i think. it installs a text file called "MOVED_STUFF.txt" that details that. that's why i tried using the yaml config file.

i've now removed the scsynth reference, so it's just 
sclang: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang

which is a little different than what it says on this website
sclang: /Applications/SuperCollider/SuperCollider.app/Contents/Resources/sclang

i opened the dev console and typed shft-cmd-k and i get these errors:

Unhandled promise rejection Object with error: YAMLException
mark: undefined
message: "JS-YAML: unacceptable kind of an object to dump [object Undefined]"
name: "YAMLException"
reason: "unacceptable kind of an object to dump [object Undefined]"
__proto__: YAMLException index.js:14
(anonymous function) events.js:87
emitTwo events.js:169
emit
/Users/jeffblanding/.atom/packages/supercollider/node_modules/q/q.js:1059
(anonymous function)
/Users/jeffblanding/.atom/packages/supercollider/node_modules/q/q.js:137
runSingle
/Users/jeffblanding/.atom/packages/supercollider/node_modules/q/q.js:130
flushnode.js:357
_tickCallback

**Comment by 3nki** [comment]
i also tried it with the yaml config file empty, same errors but it is reading the config file, i can see the path to sclang change:

config
configFile:	/Users/jeffblanding/.supercollider.yaml
sclang:	/Applications/SuperCollider/SuperCollider.app/Contents/Resources/sclang
booting
config
configFile:	/Users/jeffblanding/.supercollider.yaml
sclang:	/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
booting

**Comment by crucialfelix** [comment]
That looks like a yaml syntax error while parsing your config file. 

I should have caught that and reported it correctly.

post the whole yaml file here.  mine:

```yaml
sclang: /Users/crucial/code/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
scsynth: /Users/crucial/code/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/scsynth
sclang_conf: ~/Library/Application Support/SuperCollider/sclang_conf.yaml
debug: true
```

**Comment by crucialfelix** [comment]
btw. there is a new alpha with fixes to many things: https://github.com/supercollider/supercollider/releases

**Comment by 3nki** [comment]
ok, i got the latest alpha and checked it runs fine. the files (sclang etc) are in the same place.

here is my .supercollider.yaml file contents:

sclang: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang

**Comment by crucialfelix** [comment]
Well that's good. Though I hate it when bugs disappear without knowing why.

Now I realize that the error happened while it was creating the config file. Some undefined value was in there. I can replicate it and will fix.

**Comment by 3nki** [comment]
no it still doesn't work in Atom, i meant it runs fine itself, in it's own IDE.

**Comment by crucialfelix** [comment]
I think its definitely fixed now. Check for the update and let me know.

**Comment by crucialfelix** [comment]
I also added extra checking to detect if the path to sclang is wrong or if the config file exists and it reports issues in the post window.
