### ISSUE TITLE
"Library is uncompiled": Unhandled promise rejection Object with error: ReferenceError: fs is not defined

### ISSUE THREAD

**Issue by unclewalter** [crucialfelix/atom-supercollider#47]
It won't compile the library and so won't do anything at all beyond that. I have SuperCollider installed in the correct location. The console comes up with a reference error when I try to compile the library.

<img width="1163" alt="screen shot 2015-07-04 at 11 14 00 pm" src="https://cloud.githubusercontent.com/assets/5734225/8512148/aed64a48-2379-11e5-9872-15bdebc6c1cd.png">

<img width="688" alt="screen shot 2015-07-04 at 11 03 11 pm" src="https://cloud.githubusercontent.com/assets/5734225/8512149/b96d7896-2379-11e5-92b1-f71c55b5e693.png">

**Comment by crucialfelix** [comment]
Very strange that it worked for me. There was an obvious missing import but with coffeescript I don't see any warnings about missing variables as I would with javascript.  Fixed with a new version published

**Comment by unclewalter** [comment]
It got a little bit further. Here's what comes up now:

<img width="735" alt="screen shot 2015-07-06 at 1 33 58 pm" src="https://cloud.githubusercontent.com/assets/5734225/8515331/fadeab78-23e3-11e5-8dd3-c7cdecb043b1.png">

**Comment by crucialfelix** [comment]
It looks like you are using a 3.6 version of supercollider. True ?

The cache variable was introduced only in the new version of Quarks.

I should probably explicitly state that only 3.7+ is supported.  I had
previously intended to support 3.6 as well.

**Comment by unclewalter** [comment]
Updated to SuperCollider 3.7alpha1. It can got a little further again. Supercollider boots now, but there is no sound I issue it commands from Atom and I get this when I try to compile the library now:
<img width="737" alt="screen shot 2015-07-06 at 5 22 27 pm" src="https://cloud.githubusercontent.com/assets/5734225/8517427/2f64530a-2404-11e5-9456-b365021df603.png">

**Comment by crucialfelix** [comment]
That's fine: it did compile. 

The ERROR thing about the Document class should be a warning, but that's how supercollider is posting it right now. We have an issue filed to clean that up so it doesn't confuse people.

If you aren't getting sound then its something with your code or your speakers/audio interface.

```supercollider
Server.default.boot;

{
  SinOsc.ar(440) * 0.1
}.play
```

**Comment by unclewalter** [comment]
Not quite. My code runs fine in the SuperCollider IDE and with Sublime and but not at all here.

**Comment by crucialfelix** [comment]
You say that the sound doesn't work.

Does the interpreter work ?

```
1 + 1
```

**Comment by unclewalter** [comment]
The interpreter works. A little further investigation yields the following: 

It seems there are multiple problems here. Your code works. As does a lot of stuff, though intermittently. I might fire off a piece of code such as triggering a Synth 10 times and it only plays once or twice. This is consistent with both this newer version of SuperCollider, Sublime and in Atom. This wasn't an issue before. There seems to be a real performance hit in this version. The server takes a lot longer to boot than it did before and there seem to be a lot of bugs. And I did a clean install of it. When I roll the version back to 3.6.6, these issues disappear except for of course Atom not working since < 3.7 versions are not supported as you mentioned earlier.

One of my full pieces (https://gist.github.com/unclewalter/96cf5774f923821e6c02) plays in the IDE and with Sublime, but not in Atom, where it just yields this error: 
<img width="160" alt="screen shot 2015-07-07 at 1 28 39 am" src="https://cloud.githubusercontent.com/assets/5734225/8526095/e5b1bfd8-2447-11e5-861c-a1c077709c8c.png">

which I think is a separate issue and more to do with the setup in Atom. The other issues, seem more to do with this version of SuperCollider.

**Comment by crucialfelix** [comment]
That sounds really strange. Don't assume its because of "this version" though. Something else is going on with your installation. Everybody else would also be screaming if the entire thing was unusable like that.

lightening fast for me:
```
s.boot
```

If you go into Packages > SuperCollider you can turn on debug which should post a bit more to the internal console. Open that with option-cmd-i

That would show the full JSON dump of that error. For some reason the file is null

**Comment by unclewalter** [comment]
That something else is a mystery to me.

As far as Atom is concerned this is what I get: <img width="1167" alt="screen shot 2015-07-08 at 3 40 54 am" src="https://cloud.githubusercontent.com/assets/5734225/8552914/4dee42ca-2523-11e5-985d-fccc67094ddf.png">

**Comment by crucialfelix** [comment]
I filed a new issue: https://github.com/crucialfelix/atom-supercollider/issues/48
