### ISSUE TITLE
random subset of postlns do not arrive in post window

### ISSUE THREAD

**Issue by howthebodyworks** [crucialfelix/atom-supercollider#52]
So when I am debugging my custom Pattern/Stream The Supercollder Way(tm), i.e. by lighting an incense stick in a shrine dedicated to step debuggers, then turning around and inserting many postcs/postln statements in succession into the code

I notice there is a problem: Many of the post statements never show up. It seems to be a random subset; The first few always turn up. The later ones, it depends, usually not though. It requires a fair few statements to occur, so I'll give a long example

Here's an actual example of an init method I am trying to fix

First, I extend Object with this handy debugging statement

    + Object {
	labelledpostcs{ arg key ... args;
		[key, this].addAll(args).postcs;
		^this; //unnecessary but unambiguous
	}
	labelledpostln{ arg key ... args;
		[key, this].addAll(args).postln;
		^this; //unnecessary but unambiguous
	}
    }

Now I use it 

    PSParamSpaceElliptic {
        // ...blah blah blah...
	initPSParamSpaceElliptic { arg loc, scale;
		nCovariates.labelledpostln(\nc0);
		names.notNil.if({
			nCovariates = (names.size + 1).labelledpostln(\nc1);
		});
		scale.isCollection.if({
			nCovariates = (scale[0].size+1).labelledpostln(\nc2)
		});
		//otherwise upcast a scalar to the right dimension
		nCovariates.labelledpostln(\nc12);
		[\hello].postln;
		covariates = Array.fill2D(this.size, nCovariates, 0.5
			).labelledpostln(\cov4);
		covariances = Array.fill2D(this.size, nCovariates,1
			).labelledpostln(\cov1);
		prProjected = Array.newFrom(loc
			).labelledpostln(\pp);
	}
        // ....blah blah blah...
    }

I expect to see a bunch of debugging posts, ones starting with \nc1, \nc2, \nc12, \hello, \cov4, \cov1, \pp

Instead I see various different subsets. sometimes

 
![screen shot 2015-12-05 at 07 44 32](https://cloud.githubusercontent.com/assets/21740/11604207/6cbeab50-9b24-11e5-903b-2aaba1c5ca52.png)

sometimes
![screen shot 2015-12-05 at 07 44 25](https://cloud.githubusercontent.com/assets/21740/11604209/72f3769a-9b24-11e5-87ba-bf9b3461054c.png)

but *never* the whole set. specifically, \hello2 is never reached.

**Comment by howthebodyworks** [comment]
FWIW, thanks @crucialfelix, it's still better than 99% of every output ever being about how my FunctionDef contains variable declarations and so will not be inlined.

**Comment by crucialfelix** [comment]
I assume you've run the same code in SC IDE and it always does post there.

Your example doesn't have a `hello2` but of course I can't see the whole code.

Is this posting a huge amount of stuff quickly ? It could be sc that is messing up. if the compile strings are greater than something like 2048 it might screw up in printing the line.

btw. you know you can do `thing.debug(label)` — its the same as .labelledpostln except without the extra args.

try using that to see if it makes a difference. the implementation uses `Post << thing` rather than thing.asCompileString. So it would use item.printOn rather than item.storeOn, so it won't print the full array if it is large.

**Comment by howthebodyworks** [comment]
oh! never noticed that `debug` trick before, thanks.

Bah, yes, sorry, missing the "hello2" bit in my example - copying and pasting code bits from large projects is a losing proposition; I'll try to make a reduced test case. But yes, the same code in the SCIDE prints all lines.

Update:

Wow, making a reduced test case is hard. The problem seems to only manifest inside my reasonably convoluted, very-forky code with lots of debug statements inside patterns. But trying to do just any old set of forks doesn't work, e.g. the following prints just fine.

    10.do({|i|{Array.series(3000,0,1).debug(\foo++i);}.fork})

In fact, the non-forked version does produce a minor output truncation:

    10.do({|i|Array.series(3000,0,1).debug(\foo++i);})

The 10th line of output in that case is truncated (on my machine) after the array entry with value 2157, which is a hell of a lot more that 2048 characters, so I won't post the output here.

It's truncated at element 2151 if I use postcs instead, which is consistent with some buffer or other getting full, but not the same as random, rather small, posts being dropped sometimes. 

I'll keep hacking around and see if I can get a minimal testcase.

**Comment by crucialfelix** [comment]
It's the forks. see #70 

I've got a fix now.

**Comment by crucialfelix** [comment]
New release is out now. Sorry I didn't work on this one before but it's been a busy time since December (new baby !)
