### ISSUE TITLE
ability to copy and past from post window

### ISSUE THREAD

**Issue by howthebodyworks** [crucialfelix/atom-supercollider#53]
Here's an enhancement idea: When posting #52  I had to screenshot the post window to report the bug.

Maybe one should be able to copy and paste?

**Comment by crucialfelix** [comment]
Yes, it used to work and Electron broke it somehow. That's the app framework that Atom uses has copy and paste disabled by default on all windows.

**Comment by crucialfelix** [comment]
fixed. the "deprecation cop" demanded that I remove that, but he seems to be gone now. I put the copy support back in.
