### ISSUE TITLE
repl.coffee not found

### ISSUE THREAD

**Issue by dudat** [crucialfelix/atom-supercollider#54]
hi
i've been using atom+sc package on ubuntu without problem, on windows it seems to can't compile the sc libray and it seems to get stuck on a not  found file.
i've written the preference .yalm.supercollider with:

sclang: C:\Program Files\SuperCollider-3.6.6\sclang.exe

but atom gives me that:

Uncaught Error: ENOENT: no such file or directory, uv_chdir
/C:/Users/Administrator/.atom/packages/supercollider/lib/repl.coffee:81

but if i try to boot with supercopair he finds the sclang and works
is there any mistakes ?

**Comment by crucialfelix** [comment]
I think the first title was correct: its "interpret.scd" not found and this error happened in repl.coffee line 81

You should be on version 0.6.1 of atom-supercollider. Can you double check that ?

"interpret.scd" was removed in supercollider.js in version 0.9.0  Atom should have installed the new supercollider.js and should now be using it.  

The only way it could ask for interpret.scd is if it failed to update correctly. Maybe there was an install failure and it failed to update its dependency on supercollider.js properly.  Try the atom command: "Update package dependencies" and see if it fixes it.

If its still wrong, can you look in the package (go to Settings > Packages, search for supercollider, click on it, View Code) and see what is in node_modules/supercollider/package.json : check the version number.

**Comment by dudat** [comment]
hi! thanks for the reply!
i have a problem with interpret.scd with supercopair, he finds the sclang but get stuck on interpret.scd not found, so now i have uninstalled it and i have left only supercollider. are the problems interconnected ?
while it's updating the dependencies and i have checked the package.json version, it's:

"name": "supercolliderjs",
  "description": "Tools for working with the SuperCollider music language environment",
  "version": "0.9.3"

**Comment by dudat** [comment]
so, if i open a file and the i open a new windows, everything is been compiled but when i try to execute a command nothing happens! :\

**Comment by crucialfelix** [comment]
I think you just needed to update atom-supercollider. interpret.scd has been gone since 0.9.0

feel free to re-open this if you are still having any problem.
