### ISSUE TITLE
Better reporting when Class-initClassTree fails on startup

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/atom-supercollider#58]
Atom 1.7.3
OSX 10.10.5
SC 3.7.0-beta1

When trying to compile in Atom this error message shows up: 
`config
sclang:	/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
sclang:	/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
booting
init_OSC
empty
compiling class library...
...
	NumPrimitives = 710
	compiling dir: '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	compiling dir: '/Users/tatecarson/Library/Application Support/SuperCollider/Extensions'
Open ended string ... started on line 66 in file '/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/sc-lib-master/couchdb.sc'
Open ended string ... started on line 230 in file '/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/sc-lib-master/gepLoader.sc'
	compiling dir: '/Users/tatecarson/.atom/packages/supercollider/node_modules/supercolliderjs/lib/sc-classes'
	pass 1 done
ERROR: Class extension for nonexistent class 'Document'
     In file:'/deprecated/3.7/deprecated-3.7.sc'
ERROR: Class extension for nonexistent class 'Spherical'
     In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/3Dj-master/supercollider/Extensions/plus/plusSpherical_SS.sc'
ERROR: Class extension for nonexistent class 'Cartesian'
     In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/3Dj-master/supercollider/Extensions/plus/plusSpherical_SS.sc'
ERROR: Class extension for nonexistent class 'RealVector'
     In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/quarks/DissonanceLib/classes/HarmonicVector.sc'
ERROR: Class extension for nonexistent class 'Document'
     In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/quarks/lfsaw.de/wordBins.sc'
ERROR: Class extension for nonexistent class 'Rational'
     In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/sc_utils-master/JustIntonationTools.sc'
ERROR: Class extension for nonexistent class 'Rational'
     In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/sc_utils-master/SternBrocotTree.sc'
ERROR: Class extension for nonexistent class 'Matrix'
     In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/sc_utils-master/SternBrocotTree.sc'
ERROR: Class extension for nonexistent class 'TuningRatios'
     In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/tuningClasses/extTuningRatios.sc'
	numentries = 2859968 / 102303464 = 0.028
	14887 method selectors, 6872 classes
	method table size 71302312 bytes, big table size 818427712
	Number of Symbols 38009
	Byte Code Size 1758999
	compiled 1521 files in 3.24 seconds

Info: 26 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done

Execution warning: Class 'Document' not found
compiling tunings
Execution warning: Class 'CV' not found

SUPERCOLLIDERJS:0:START:Error
SUPERCOLLIDERJS:0:CHUNK:{"selector": "isMetaClass","what": "DoesNotUnderstandError","args": [],"receiver": {"asString": "nil","class": "Nil"},"class": "DoesNotUnderstandError","errorString": "ERROR: Message 'isMetaClass' not understood.","backtrace": [{"caller": "0x1156bc640","charPos": 4283,"file": "/Users/tatecarson/.atom/packages/supercollider/node_modules/supercolliderjs/lib/sc-classes/SuperColliderJS.sc","class": "Meta_SuperColliderJS","args": [{"name": "this","value": {"asString": "SuperColliderJS","class": "Meta_SuperColliderJS"}},{"name": "err","value": {"asString": "a DoesNotUnderstandError","class": "DoesNotUnderstandError","vars": [{"name": "what","value": {"asString": "'DoesNotUnderstandError'","class": "Symbol"}},{"name": "protectedBacktrace","value": {"asString": "nil","class": "Nil"}},{"name": "path","value": {"asString": "nil","class": "Nil"}},{"name": "receiver","value": {"asString": "nil","class": "Nil"}},{"name": "selector","value": {"asString": "'isMetaClass'","class": "Symbol"}},{"name": "args","value": {"asString": "[  ]","class": "Array"}}]}},{"name": "compiledFunc","value": {"asString": "nil","class": "Nil","vars": []}}],"vars": [{"name": "out","value": {"asString": "[  ]","class": "Array","vars": []}},{"name": "currentFrame","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "def","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "ownerClass","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "methodName","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "callerAddress","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "startAtDef","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "stopAtDef","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "addingFrame","value": {"asString": "false","class": "False","vars": []}}],"type": "Method","method": "getBacktrace","address": "0x1156bea40"},{"caller": "0x1184eec40","charPos": 2644,"file": "/Users/tatecarson/.atom/packages/supercollider/node_modules/supercolliderjs/lib/s
SUPERCOLLIDERJS:0:CHUNK:c-classes/SuperColliderJS.sc","class": "Meta_SuperColliderJS","args": [{"name": "this","value": {"asString": "SuperColliderJS","class": "Meta_SuperColliderJS"}},{"name": "err","value": {"asString": "a DoesNotUnderstandError","class": "DoesNotUnderstandError","vars": [{"name": "what","value": {"asString": "'DoesNotUnderstandError'","class": "Symbol"}},{"name": "protectedBacktrace","value": {"asString": "nil","class": "Nil"}},{"name": "path","value": {"asString": "nil","class": "Nil"}},{"name": "receiver","value": {"asString": "nil","class": "Nil"}},{"name": "selector","value": {"asString": "'isMetaClass'","class": "Symbol"}},{"name": "args","value": {"asString": "[  ]","class": "Array"}}]}},{"name": "getBacktrace","value": {"asString": "true","class": "True","vars": []}},{"name": "compiledFunc","value": {"asString": "nil","class": "Nil","vars": []}}],"vars": [{"name": "data","value": {"asString": "( 'selector': isMetaClass, 'what': DoesNotUnderstandError, 'args': [  ], 'receiver': ( 'asString': nil, 'class': class Nil ),   'class': class DoesNotUnderstandError, 'errorString': ERROR: Message 'isMetaClass' not understood. )","class": "Event","vars": [{"name": "array","value": {"asString": "[ nil, nil, nil, nil, selector, isMetaClass, what, DoesNotUnderstandError, args, [  ], receiver, ( 'asString': nil, 'class': class Nil ), class, class DoesNotUnderstandError, errorString, ERROR: Message 'isMetaClass' not understood., nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil ]","class": "Array"}},{"name": "size","value": {"asString": "6","class": "Integer"}},{"name": "proto","value": {"asString": "nil","class": "Nil"}},{"name": "parent","value": {"asString": "nil","class": "Nil"}},{"name": "know","value": {"asString": "true","class": "True"}}]}}],"type": "Method","method": "encodeError","address": "0x1156bc640"},{"caller": "0x1157bfb40","address": "0x1184eec40","context": "SuperColliderJS","vars": [{"name": "error","value": {"asString": "nil","class": "Nil","vars": []}}],"type": "Function"},{"c
SUPERCOLLIDERJS:0:CHUNK:aller": "0x1157bf600","charPos": 4541,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Function.sc","class": "Function","args": [{"name": "this","value": {"asString": "a Function","class": "Function","vars": [{"name": "def","value": {"asString": "< FunctionDef in Method Exception:reportError >","class": "FunctionDef"}},{"name": "context","value": {"asString": "Frame (0x1147ef748) of Exception:reportError","class": "Frame"}}]}}],"vars": [{"name": "result","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "thread","value": {"asString": "a Thread","class": "Thread","vars": [{"name": "state","value": {"asString": "0","class": "Integer"}},{"name": "func","value": {"asString": "nil","class": "Nil"}},{"name": "stack","value": {"asString": "nil","class": "Nil"}},{"name": "method","value": {"asString": "nil","class": "Nil"}},{"name": "block","value": {"asString": "nil","class": "Nil"}},{"name": "frame","value": {"asString": "nil","class": "Nil"}},{"name": "ip","value": {"asString": "0x0","class": "RawPointer"}},{"name": "sp","value": {"asString": "0x0","class": "RawPointer"}},{"name": "numpop","value": {"asString": "0","class": "Integer"}},{"name": "receiver","value": {"asString": "nil","class": "Nil"}},{"name": "numArgsPushed","value": {"asString": "0","class": "Integer"}},{"name": "parent","value": {"asString": "nil","class": "Nil"}},{"name": "terminalValue","value": {"asString": "nil","class": "Nil"}},{"name": "primitiveError","value": {"asString": "5000","class": "Integer"}},{"name": "primitiveIndex","value": {"asString": "141","class": "Integer"}},{"name": "randData","value": {"asString": "Int32Array[ 1336278640, -1109901115, 1763859480, 0 ]","class": "Int32Array"}},{"name": "beats","value": {"asString": "3.333749467","class": "Float"}},{"name": "seconds","value": {"asString": "3.333749467","class": "Float"}},{"name": "clock","value": {"asString": "SystemClock","class": "Meta_SystemClock"}},{"name": "nextBeat","value": {"asString": "nil","class": "Nil
SUPERCOLLIDERJS:0:CHUNK:"}},{"name": "endBeat","value": {"asString": "nil","class": "Nil"}},{"name": "endValue","value": {"asString": "nil","class": "Nil"}},{"name": "environment","value": {"asString": "nil","class": "Nil"}},{"name": "exceptionHandler","value": {"asString": "a Function","class": "Function"}},{"name": "threadPlayer","value": {"asString": "nil","class": "Nil"}},{"name": "executingPath","value": {"asString": "nil","class": "Nil"}},{"name": "oldExecutingPath","value": {"asString": "nil","class": "Nil"}}]}},{"name": "next","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "wasInProtectedFunc","value": {"asString": "false","class": "False","vars": []}}],"type": "Method","method": "prTry","address": "0x1157bfb40"},{"caller": "0x11531d440","charPos": 4422,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Function.sc","class": "Function","args": [{"name": "this","value": {"asString": "a Function","class": "Function","vars": [{"name": "def","value": {"asString": "< FunctionDef in Method Exception:reportError >","class": "FunctionDef"}},{"name": "context","value": {"asString": "Frame (0x1147ef748) of Exception:reportError","class": "Frame"}}]}},{"name": "handler","value": {"asString": "a Function","class": "Function","vars": [{"name": "def","value": {"asString": "< FunctionDef in Method Exception:reportError >","class": "FunctionDef"}},{"name": "context","value": {"asString": "Frame (0x1147ef748) of Exception:reportError","class": "Frame"}}]}}],"vars": [{"name": "result","value": {"asString": "nil","class": "Nil","vars": []}}],"type": "Method","method": "try","address": "0x1157bf600"},{"caller": "0x116c90a80","charPos": 425,"file": "/Users/tatecarson/.atom/packages/supercollider/node_modules/supercolliderjs/lib/sc-classes/SystemOverwrites/plusError.sc","class": "Exception","args": [{"name": "this","value": {"asString": "a DoesNotUnderstandError","class": "DoesNotUnderstandError","vars": [{"name": "what","value": {"asString": "'DoesNotUnderstandError'","class": "Symb
SUPERCOLLIDERJS:0:CHUNK:ol"}},{"name": "protectedBacktrace","value": {"asString": "nil","class": "Nil"}},{"name": "path","value": {"asString": "nil","class": "Nil"}},{"name": "receiver","value": {"asString": "nil","class": "Nil"}},{"name": "selector","value": {"asString": "'isMetaClass'","class": "Symbol"}},{"name": "args","value": {"asString": "[  ]","class": "Array"}}]}}],"type": "Method","method": "reportError","address": "0x11531d440"},{"caller": "0x116097000","charPos": 2017,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Nil.sc","class": "Nil","args": [{"name": "this","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "error","value": {"asString": "a DoesNotUnderstandError","class": "DoesNotUnderstandError","vars": [{"name": "what","value": {"asString": "'DoesNotUnderstandError'","class": "Symbol"}},{"name": "protectedBacktrace","value": {"asString": "nil","class": "Nil"}},{"name": "path","value": {"asString": "nil","class": "Nil"}},{"name": "receiver","value": {"asString": "nil","class": "Nil"}},{"name": "selector","value": {"asString": "'isMetaClass'","class": "Symbol"}},{"name": "args","value": {"asString": "[  ]","class": "Array"}}]}}],"type": "Method","method": "handleError","address": "0x116c90a80"},{"caller": "0x113fff4c0","charPos": 2077,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Thread.sc","class": "Thread","args": [{"name": "this","value": {"asString": "a Thread","class": "Thread","vars": [{"name": "state","value": {"asString": "0","class": "Integer"}},{"name": "func","value": {"asString": "nil","class": "Nil"}},{"name": "stack","value": {"asString": "nil","class": "Nil"}},{"name": "method","value": {"asString": "nil","class": "Nil"}},{"name": "block","value": {"asString": "nil","class": "Nil"}},{"name": "frame","value": {"asString": "nil","class": "Nil"}},{"name": "ip","value": {"asString": "0x0","class": "RawPointer"}},{"name": "sp","value": {"asString": "0x0","class": "RawPointer"}},{"name": "nu
SUPERCOLLIDERJS:0:CHUNK:mpop","value": {"asString": "0","class": "Integer"}},{"name": "receiver","value": {"asString": "nil","class": "Nil"}},{"name": "numArgsPushed","value": {"asString": "0","class": "Integer"}},{"name": "parent","value": {"asString": "nil","class": "Nil"}},{"name": "terminalValue","value": {"asString": "nil","class": "Nil"}},{"name": "primitiveError","value": {"asString": "5000","class": "Integer"}},{"name": "primitiveIndex","value": {"asString": "141","class": "Integer"}},{"name": "randData","value": {"asString": "Int32Array[ 1336278640, -1109901115, 1763859480, 0 ]","class": "Int32Array"}},{"name": "beats","value": {"asString": "3.333749467","class": "Float"}},{"name": "seconds","value": {"asString": "3.333749467","class": "Float"}},{"name": "clock","value": {"asString": "SystemClock","class": "Meta_SystemClock"}},{"name": "nextBeat","value": {"asString": "nil","class": "Nil"}},{"name": "endBeat","value": {"asString": "nil","class": "Nil"}},{"name": "endValue","value": {"asString": "nil","class": "Nil"}},{"name": "environment","value": {"asString": "nil","class": "Nil"}},{"name": "exceptionHandler","value": {"asString": "a Function","class": "Function"}},{"name": "threadPlayer","value": {"asString": "nil","class": "Nil"}},{"name": "executingPath","value": {"asString": "nil","class": "Nil"}},{"name": "oldExecutingPath","value": {"asString": "nil","class": "Nil"}}]}},{"name": "error","value": {"asString": "a DoesNotUnderstandError","class": "DoesNotUnderstandError","vars": [{"name": "what","value": {"asString": "'DoesNotUnderstandError'","class": "Symbol"}},{"name": "protectedBacktrace","value": {"asString": "nil","class": "Nil"}},{"name": "path","value": {"asString": "nil","class": "Nil"}},{"name": "receiver","value": {"asString": "nil","class": "Nil"}},{"name": "selector","value": {"asString": "'isMetaClass'","class": "Symbol"}},{"name": "args","value": {"asString": "[  ]","class": "Array"}}]}}],"type": "Method","method": "handleError","address": "0x116097000"},{"caller": "0x113ffd3c0","charPos": 7827,"file": "/App
SUPERCOLLIDERJS:0:CHUNK:lications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Object.sc","class": "Object","args": [{"name": "this","value": {"asString": "a DoesNotUnderstandError","class": "DoesNotUnderstandError","vars": [{"name": "what","value": {"asString": "'DoesNotUnderstandError'","class": "Symbol"}},{"name": "protectedBacktrace","value": {"asString": "nil","class": "Nil"}},{"name": "path","value": {"asString": "nil","class": "Nil"}},{"name": "receiver","value": {"asString": "nil","class": "Nil"}},{"name": "selector","value": {"asString": "'isMetaClass'","class": "Symbol"}},{"name": "args","value": {"asString": "[  ]","class": "Array"}}]}}],"type": "Method","method": "throw","address": "0x113fff4c0"},{"caller": "0x1173f5f00","charPos": 7158,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Object.sc","class": "Object","args": [{"name": "this","value": {"asString": "nil","class": "Nil","vars": []}},{"name": "selector","value": {"asString": "'isMetaClass'","class": "Symbol","vars": []}},{"name": "args","value": {"asString": "nil","class": "Nil","vars": []}}],"type": "Method","method": "doesNotUnderstand","address": "0x113ffd3c0"},{"caller": "0x1153a0880","charPos": 1130,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Kernel.sc","class": "Meta_Class","args": [{"name": "this","value": {"asString": "Class","class": "Meta_Class"}},{"name": "aClass","value": {"asString": "nil","class": "Nil","vars": []}}],"vars": [{"name": "implementsInitClass","value": {"asString": "nil","class": "Nil","vars": []}}],"type": "Method","method": "initClassTree","address": "0x1173f5f00"},{"caller": "0x1173f5f00","charPos": 557,"file": "/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/quarks/redSys/redMixer/RedMixerChannelGUI.sc","class": "Meta_RedMixerChannelGUI","args": [{"name": "this","value": {"asString": "RedMixerChannelGUI","class": "Meta_RedMixerChannelGUI"}}],"type": "Method","method": "init
SUPERCOLLIDERJS:0:CHUNK:Class","address": "0x1153a0880"},{"caller": "0x116f20b80","charPos": 1130,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Kernel.sc","class": "Meta_Class","args": [{"name": "this","value": {"asString": "Class","class": "Meta_Class"}},{"name": "aClass","value": {"asString": "RedMixerChannelGUI","class": "Meta_RedMixerChannelGUI"}}],"vars": [{"name": "implementsInitClass","value": {"asString": "nil","class": "Nil","vars": []}}],"type": "Method","method": "initClassTree","address": "0x1173f5f00"},{"caller": "0x1173f5f00","charPos": 5243,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Collections/ArrayedCollection.sc","class": "ArrayedCollection","args": [{"name": "this","value": {"asString": "[ class RedLoop, class SBufControlView, class C28Voice, class RedGAPhenomeToDefNum, class GrainPicCursor, class MxDocument, class KorgNative, class DoOnceIn, class SpatialRender, class SNPInfo, class Ratio, class GA, class LED, class MBControlPanel, class BMAbstractGUI, class TDuty_old, class HighShelf, class OSCFileLog, class FlowVar, class AudioFlux, class NLC_BufCombine, class ZLPF, class FoaPress, class GAWorkbench, class Segmentation, class UGepTimeAnalyzer, class ScorePresetMenu, class BusListGui, cla...etc...","class": "Array","vars": []}},{"name": "function","value": {"asString": "a Function","class": "Function","vars": [{"name": "def","value": {"asString": "< FunctionDef in Method Meta_Class:initClassTree >","class": "FunctionDef"}},{"name": "context","value": {"asString": "Frame (0x114866ee8) of Meta_Class:initClassTree","class": "Frame"}}]}}],"vars": [{"name": "i","value": {"asString": "852","class": "Integer","vars": []}}],"type": "Method","method": "do","address": "0x116f20b80"},{"caller": "0x114e2f280","charPos": 1130,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Kernel.sc","class": "Meta_Class","args": [{"name": "this","value": {"asString": "Class","class": "M
SUPERCOLLIDERJS:0:CHUNK:eta_Class"}},{"name": "aClass","value": {"asString": "Object","class": "Meta_Object"}}],"vars": [{"name": "implementsInitClass","value": {"asString": "nil","class": "Nil","vars": []}}],"type": "Method","method": "initClassTree","address": "0x1173f5f00"},{"caller": "0x114e38ec0","charPos": 5040,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Core/Kernel.sc","class": "Process","args": [{"name": "this","value": {"asString": "a Main","class": "Main"}}],"vars": [{"name": "time","value": {"asString": "3.334242063","class": "Float","vars": []}}],"type": "Method","method": "startup","address": "0x114e2f280"},{"charPos": 217,"file": "/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/DefaultLibrary/Main.sc","class": "Main","args": [{"name": "this","value": {"asString": "a Main","class": "Main"}}],"vars": [{"name": "didWarnOverwrite","value": {"asString": "false","class": "False","vars": []}}],"type": "Method","method": "startup","address": "0x114e38ec0"}]}
SUPERCOLLIDERJS:0:END:Error
compileError`

before trying to run any code. Not sure about the yaml file or where I would put it. 

thanks

**Comment by crucialfelix** [comment]
It looks like the problem is that you have various things in your extensions folders but you don't have the quarks installed that those extensions refer to. Also you probably have some quarks installed that depend on other ones that aren't installed.

You manually moved these files into your Extensions folder:

```
ERROR: Class extension for nonexistent class 'TuningRatios'
In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/tuningClasses/extTuningRatios.sc'
```

Which would be fine, this is just a warning. The compiler ignores those class extensions and just moves on.

But then:

```
Execution warning: Class 'Document' not found
compiling tunings
Execution warning: Class 'CV' not found
```

This was an error that happened while supercollider was running its startup. After it compiles the library (which succeeds) it then calls *initClass on every class. (supercollider should post that it is starting initClass and then finishing. that would make it more obvious to people)

Something you have in there failed, so supercollider threw an error and stopped. Because class initialization failed, SuperColliderJS didn't get to initialize itself (it failed before it got to SuperColliderJS.initClass) and it's not set up to communicate with atom. 

That's why you got a messy raw error dump here.

I can figure out how to get around this failure on startup.

You will get the exact same errors on startup if you use the standard SC IDE.

What you should probably do is remove those files from Extensions and remove all Quarks. Then reinstall just the ones you need. SuperCollider is not very good at handling these conflicts and it falls over dead far too easily. That's something I can probably handle better with atom-supercollider to at least inform people what the state of their system is and what the problem might be.

Never mind about the yaml file, its only important if you have SuperCollider installed in some strange place. 

> If you've installed SuperCollider in a non-standard place or have a development build, then create a .supercollider.yaml file to specify the path where sclang can be found.

**Comment by tatecarson** [comment]
I did a full reinstall and it works now. I’ve been meaning to do this for a while but finally was able to with the summer. Thanks for your help, excited to get into Atom. 

-- 
Tate Carson
Sent with Airmail

On May 10, 2016 at 1:12:04 AM, Chris Sattinger (notifications@github.com) wrote:

It looks like the problem is that you have various things in your extensions folders but you don't have the quarks installed that those extensions refer to. Also you probably have some quarks installed that depend on other ones that aren't installed.

You manually moved these files into your Extensions folder:

ERROR: Class extension for nonexistent class 'TuningRatios'
In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/tuningClasses/extTuningRatios.sc'

Which would be fine, this is just a warning. The compiler ignores those class extensions and just moves on.

But then:

Execution warning: Class 'Document' not found
compiling tunings
Execution warning: Class 'CV' not found

This was an error that happened while supercollider was running its startup. After it compiles the library (which succeeds) it then calls *initClass on every class. (supercollider should post that it is starting initClass and then finishing. that would make it more obvious to people)

Something you have in there failed, so supercollider threw an error and stopped. Because class initialization failed, SuperColliderJS didn't get to initialize itself (it failed before it got to SuperColliderJS.initClass) and it's not set up to communicate with atom.

That's why you got a messy raw error dump here.

I can figure out how to get around this failure on startup.

You will get the exact same errors on startup if you use the standard SC IDE.

What you should probably do is remove those files from Extensions and remove all Quarks. Then reinstall just the ones you need. SuperCollider is not very good at handling these conflicts and it falls over dead far too easily. That's something I can probably handle better with atom-supercollider to at least inform people what the state of their system is and what the problem might be.

Never mind about the yaml file, its only important if you have SuperCollider installed in some strange place.

If you've installed SuperCollider in a non-standard place or have a development build, then create a .supercollider.yaml file to specify the path where sclang can be found.

**Comment by tatecarson** [comment]
Trying to get the class lookup going and having trouble following your directions. I have ctags. Here are a few questions: 

1. When you say make the file named ~/.ctags what exactly does that mean? is that a txt file that should then contain that text? 

2. I sort of know what a symlink is but what’s the best way to make one? Also, when you say “project directory” what exactly do you mean? The atom directory? The supercollider directory? Where I keep my scds? Will I have to do this if I put projects into different folders? 

thanks,  

-- 
Tate Carson
Sent with Airmail

On May 10, 2016 at 3:12:25 PM, Tate Carson (tate.carson@gmail.com) wrote:

I did a full reinstall and it works now. I’ve been meaning to do this for a while but finally was able to with the summer. Thanks for your help, excited to get into Atom. 

-- 
Tate Carson
Sent with Airmail

On May 10, 2016 at 1:12:04 AM, Chris Sattinger (notifications@github.com) wrote:

It looks like the problem is that you have various things in your extensions folders but you don't have the quarks installed that those extensions refer to. Also you probably have some quarks installed that depend on other ones that aren't installed.

You manually moved these files into your Extensions folder:

ERROR: Class extension for nonexistent class 'TuningRatios'
In file:'/Users/tatecarson/Library/Application Support/SuperCollider/Extensions/tuningClasses/extTuningRatios.sc'


Which would be fine, this is just a warning. The compiler ignores those class extensions and just moves on.

But then:

Execution warning: Class 'Document' not found
compiling tunings
Execution warning: Class 'CV' not found


This was an error that happened while supercollider was running its startup. After it compiles the library (which succeeds) it then calls *initClass on every class. (supercollider should post that it is starting initClass and then finishing. that would make it more obvious to people)

Something you have in there failed, so supercollider threw an error and stopped. Because class initialization failed, SuperColliderJS didn't get to initialize itself (it failed before it got to SuperColliderJS.initClass) and it's not set up to communicate with atom.

That's why you got a messy raw error dump here.

I can figure out how to get around this failure on startup.

You will get the exact same errors on startup if you use the standard SC IDE.

What you should probably do is remove those files from Extensions and remove all Quarks. Then reinstall just the ones you need. SuperCollider is not very good at handling these conflicts and it falls over dead far too easily. That's something I can probably handle better with atom-supercollider to at least inform people what the state of their system is and what the problem might be.

Never mind about the yaml file, its only important if you have SuperCollider installed in some strange place.

If you've installed SuperCollider in a non-standard place or have a development build, then create a .supercollider.yaml file to specify the path where sclang can be found.

**Comment by crucialfelix** [comment]
1. Yes, a text file in your home directory called `.ctags` with that text inside it.

2. Don't mess with symlinks unless you are familiar with them. Project directory means the directory where you are working - where your .scd files are. The folder that Atom opened up and shows the files in the tree view on the left side. That is your project.

**Comment by tatecarson** [comment]
Ok, this worked when I removed the commented out text from your example ctags file and symlinked the others into the project folder. alt-cmd-down_arrow doesn’t seem to do anything but that’s ok. 
-- 
Tate Carson
Sent with Airmail

On May 11, 2016 at 3:58:10 AM, Chris Sattinger (notifications@github.com) wrote:

Yes, a text file in your home directory called .ctags with that text inside it.

Don't mess with symlinks unless you are familiar with them. Project directory means the directory where you are working - where your .scd files are. The folder that Atom opened up and shows the files in the tree view on the left side. That is your project.

**Comment by crucialfelix** [comment]
I am now using atom-ctags with autocomplete-plus

https://atom.io/packages/atom-ctags

use `Atom ctags: Rebuild` to regenerate the index if it needs it.

I need to update atom-supercollider docs for this. I had problems with symbol-gen and the standard autocomplete where it often did not go to the symbol and didn't report any problem. very annoying. 

use `Key Binding Resolver: Toggle` to see what your alt-cmd-down-arrow is triggering.

**Comment by tatecarson** [comment]
Oh good, got that working. The only thing i’m really missing from the IDE now is method reminders. I could add them as snippets I guess for things I use often but it’s usually more necessary for ugens that I don’t remember what their methods are. Just want to thank you again, atom is a much better experience than the IDE, night and day. 

-- 
Tate Carson
Sent with Airmail

On May 12, 2016 at 1:11:11 AM, Chris Sattinger (notifications@github.com) wrote:

I am now using atom-ctags with autocomplete-plus

https://atom.io/packages/atom-ctags

use Atom ctags: Rebuild to regenerate the index if it needs it.

I need to update atom-supercollider docs for this. I had problems with symbol-gen and the standard autocomplete where it often did not go to the symbol and didn't report any problem. very annoying.

use Key Binding Resolver: Toggle to see what your alt-cmd-down-arrow is triggering.

**Comment by crucialfelix** [comment]
Great to hear !

I'd like to eventually hook into the help docs and some introspection on
the class/methods. That would provide inline docs.
Even if I can just get a pane that displays the help files.

On Fri, May 13, 2016 at 9:07 AM tatecarson <notifications@github.com> wrote:

> Oh good, got that working. The only thing i’m really missing from the IDE
> now is method reminders. I could add them as snippets I guess for things I
> use often but it’s usually more necessary for ugens that I don’t remember
> what their methods are. Just want to thank you again, atom is a much better
> experience than the IDE, night and day.
>
> --
> Tate Carson
> Sent with Airmail
>
> On May 12, 2016 at 1:11:11 AM, Chris Sattinger (notifications@github.com)
> wrote:
>
> I am now using atom-ctags with autocomplete-plus
>
> https://atom.io/packages/atom-ctags
>
> use Atom ctags: Rebuild to regenerate the index if it needs it.
>
> I need to update atom-supercollider docs for this. I had problems with
> symbol-gen and the standard autocomplete where it often did not go to the
> symbol and didn't report any problem. very annoying.
>
> use Key Binding Resolver: Toggle to see what your alt-cmd-down-arrow is
> triggering.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/crucialfelix/atom-supercollider/issues/58#issuecomment-218967618>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/
