### ISSUE TITLE
Auto Indent

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/atom-supercollider#59]
Should this be working? It works how expected with cmd-shift-i under javascript syntax but in supercollider does some weird formatting. I have autoindent and auto indent on paste checked. I messed around with it a little and couldn't figure it out.

**Comment by crucialfelix** [comment]
atom-supercollider doesn't have anything to do with code formatting.  maybe the syntax affects it. are you pasting something ? what ?

**Comment by tatecarson** [comment]
This video show’s what i’m talking about: 

https://www.dropbox.com/s/vtdsuxmsacs43jy/indent.mov?dl=0

Under the javascript syntax cmd-shift-i does the logical indent. When I switch to supercollider and do the same keystroke it does this weird indent that doesn’t make any sense. It’s not matching the parentheses.  
-- 
Tate Carson
Sent with Airmail

On May 11, 2016 at 3:54:58 AM, Chris Sattinger (notifications@github.com) wrote:

atom-supercollider doesn't have anything to do with code formatting. maybe the syntax affects it. are you pasting something ? what ?

**Comment by crucialfelix** [comment]
Thanks for the video. Strange, I'll look into it.

**Comment by crucialfelix** [comment]
This seems to be something to do with not having an end-block syntax marker; or that the auto-indent function isn't as smart as it needs to be for all languages.

https://discuss.atom.io/t/coffeescript-auto-indent-broken/10951/2
https://github.com/atom/atom/issues/6655
https://github.com/TypeStrong/atom-typescript/issues/159

So it's a not-fix for me.

Atom-beautify is better but it would need an implementation for supercollider.
