### ISSUE TITLE
windows: getting compileError when trying to recompile the library

### ISSUE THREAD

**Issue by llloret** [crucialfelix/atom-supercollider#61]
When I load an .scd file, and I try to execute something on it, I get a "Library is not compiled" error.

When I select the menu option to recompile, I get a compileError message.

Funny thing is that when I select "recompile", the QT SuperCollider editor is launching and compiling the class library, and indexing the help.

And Atom is detecting when I close the QT editor windows, saying that "sclang exited".

I would really like to have this working, and see if I can help to develop it further...

**Comment by crucialfelix** [comment]
Oh that's strange. 

Maybe you have the path to sclang set to the ide. It needs to be the `sclang.exe`

**Comment by llloret** [comment]
Oops, sorry. That was a silly mistake. It works now ;).

**Comment by crucialfelix** [comment]
Splendid !  Bug reports and help very much appreciated.

One of the things I will do next is to improve the compile failure reporting. It should do some analysis, list the paths, identify duplicate file names and offer to clean up the mess.
