### ISSUE TITLE
Add a setting for sclang path

### ISSUE THREAD

**Issue by crucialfelix** [crucialfelix/atom-supercollider#62]
The documentation for creating a .supercollider.yaml file is confusing people. Just make a setting in atom for it.

**Comment by birv2** [comment]
I know this is closed, but I'm a noob here. Which file contains the atom setting for sclang.exe in Windows10? I know where Atom is looking for sclang, and I know where sclang is, but can't locate the config file so that I can make that change. TIA.

**Comment by crucialfelix** [comment]
In Atom there is a settings page for the atom-supercollider package. There is a path to sclang setting in that dialog.

The other (confusing) way I was talking about is that you can make a file called .supercollider.yaml and put it in your project directory or your home directory.

**Comment by birv2** [comment]
Thanks for the reply. I clicked on the settings page in Atom for the atom-supercollider page but didn't see where to set the path. It said what the path was set to but not where to reset it. Perhaps I'm blind!

**Comment by laelume** [comment]
Hi, in the Atom supercollider "Settings" I don't see a place you can modify the sclang path. If there is, it's quite well-hidden. Could you please specify where to find this? Thanks!

```
3. It should work
If you've installed SuperCollider in a non-standard place or have a development build, then you can set that path in the settings. (Settings View: Open)
```
is not really a transparent way to indicate where to do this since this instruction leads you to the place the instruction is located.

**Comment by woolgathering** [comment]
On my install of 0.9.1, it's right in Settings, just above Keybindings.
