### ISSUE TITLE
Tidalcycles plugin disables atom supercollder

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/atom-supercollider#65]
I just installed the new tidal distribution and it seems to interfere with atom-sc. With the tidalcycles package enabled I can compile the class library but not evaluate any code. Everything works fine when I disable the package. I wish there was some sort of error report I could list, I really have no idea what the problem is. I'll post this on their forum too and see if a solution can be found.

**Comment by crucialfelix** [comment]
Strange. I'll give it a try and see if I can figure it out.

you can open the dev tools with option-command-I and look in the console.

also open Toggle Keybinding Resolver and you can see what your keystrokes
are being intercepted by.

probably tidal is bound to shift-enter for all grammars and it should be
only active for tidal.
same with atom-supercollider: I need to change it only respond if that
grammar is active.

you can still execute code with shift-command-P and Interpret Supercollider
or whatever I named the function.
and you can rebind the keys yourself by opening your key bindings file.

On Wed, Jun 8, 2016 at 11:41 PM tatecarson <notifications@github.com> wrote:

> I just installed the new tidal distribution and it seems to interfere with
> atom-sc. With the tidalcycles package enabled I can compile the class
> library but not evaluate any code. Everything works fine when I disable the
> package. I wish there was some sort of error report I could list, I really
> have no idea what the problem is. I'll post this on their forum too and see
> if a solution can be found.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/crucialfelix/atom-supercollider/issues/65>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AANWcprrlekMx-i_YQI9aUL0VgVKHoMTks5qJzcegaJpZM4Ixbpi>
> .
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by crucialfelix** [comment]
https://github.com/tidalcycles/atom-tidalcycles/pull/1

I'm changing atom-supercollider also to limit to supercollider documents
