### ISSUE TITLE
quarks not compiling 

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/atom-supercollider#66]
Hi, 

I'm having an issue with quarks compiling in atom. It's very strange. The first time I download a quark and recompile the library the folder show's up in the post window and everything works. But if I recompile the quarks disappear again. The quarks compile fine in the IDE. I had more quarks and I uninstalled them all except for dirt-samples, superdirt, and vowel.  I guess I could just manually put quarks in the extensions folder but it seems like this normal way should be working.

**Comment by crucialfelix** [comment]
Something is definitely broken for you.

It seems like it is overwriting the config file.

**Comment by crucialfelix** [comment]
Hmm. Working fine for me.

Did you click "recompile class library" with the green button ?

When it compiles it posts the config:

```
config
configPath:	/Users/crucial/.supercollider.yaml
sclang:	/Users/crucial/code/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
sclang_conf:	~/Library/Application Support/SuperCollider/sclang_conf.yaml
```

You can open that sclang_conf file and you should see your changes as they happen.

open it in Atom and you can see the file change whenever you add or remove quarks.

There is a bug that the file should be clickable but because there is a space in the path it gets URL encoded.

So on the command line you can open it:
```
atom ~/Library/Application\ Support/SuperCollider/sclang_conf.yaml
```

**Comment by tatecarson** [comment]
Yes I pressed the green button. It does seem to be updating that sclang_config file as I add quarks. But when I recompile I get this: 

config
scaling: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
scaling: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang

It doesn’t seem like it’s finding that sclang_config file to load the quarks. 

thanks 
-- 
Tate Carson
http://www.tatecarson.com



On June 15, 2016 at 6:21:52 AM, Chris Sattinger (notifications@github.com) wrote:

Hmm. Working fine for me.

Did you click "recompile class library" with the green button ?

When it compiles it posts the config:

config
configPath: /Users/crucial/.supercollider.yaml
sclang: /Users/crucial/code/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
sclang_conf:    ~/Library/Application Support/SuperCollider/sclang_conf.yaml

You can open that sclang_conf file and you should see your changes as they happen.

open it in Atom and you can see the file change whenever you add or remove quarks.

There is a bug that the file should be clickable but because there is a space in the path it gets URL encoded.

So on the command line you can open it:

atom ~/Library/Application\ Support/SuperCollider/sclang_conf.yaml

**Comment by tatecarson** [comment]
Yes I pressed the green button. It does seem to be updating that sclang_config file as I add quarks. But when I recompile I get this: 

config
scaling: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
scaling: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang

It doesn’t seem like it’s finding that sclang_config file to load the quarks. 

thanks

**Comment by crucialfelix** [comment]
open the IDE and open preferences and see what the sclang_config path is.
is it different than what was posted in atom ?

**Comment by tatecarson** [comment]
My sclang_config file is here: ~/Library/Application Support/SuperCollider/sclang_conf.yaml . It's set to that in the IDE and is found fine. The problem though is that atom never loads it. Only - 

config
sclang: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
sclang: /Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang

sclang_conf never shows up in the post window.

**Comment by crucialfelix** [comment]
Found the problem. A new release and fix is on the way, perhaps tonight.

**Comment by crucialfelix** [comment]
will do the release soon
