### ISSUE TITLE
certain code import breaks eval shortcut

### ISSUE THREAD

**Issue by tatecarson** [crucialfelix/atom-supercollider#69]
Some very strange is happening when I try to open or copy and paste this file into atom-supercollider. 

https://www.dropbox.com/s/yqtep2ucriviwu0/dist2.scd?dl=0

It's a file output by openmusic that just generates a Pbind with the given values. Whenever I open the file in atom or even just copy and paste the code my shortcut for eval breaks if I'm not selecting anything. I still works if the whole line is selected. The strange thing is that if I delete the pbind and try to run something else then the shortcut starts working again. 

Everything works fine in the IDE. 

Any ideas?

**Comment by tatecarson** [comment]
After more testing it seems that any 2D array has the same effect. When the same array is flattened eval works again.

**Comment by crucialfelix** [comment]
```
Pbind(\freq, Pseq([[183.71933],[306.13547],[428.95813],[551.17237],[673.88556],[795.8538],[918.4303],[1041.6776],[1163.8529],[1286.9077],[1408.2551],[1530.3999],[1653.56],[1776.3412]]),\dur, Pseq([1,1,1,1,1,1,1,1,1,1,1,1,1,1]),\amp, Pseq(nil),).play;
```

The error I'm seeing is:

```
ERROR: ListPattern (Pseq) requires a non-empty collection; received nil.9:23:20.071
Meta_ListPattern:*new
Args
this	Pseq
list	nil
repeats	Integer 1
Meta_Pseq:*new
Args
this	Pseq
list	nil
repeats	Integer 1
offset	Integer 0
```

which is the 2nd Pseq. The first one is fine.

These compile fine:

```
[[183.71933],[306.13547],[428.95813],[551.17237],[673.88556],[795.8538],[918.4303],[1041.6776],[1163.8529],[1286.9077],[1408.2551],[1530.3999],[1653.56],[1776.3412]]


Pseq([[183.71933],[306.13547],[428.95813],[551.17237],[673.88556],[795.8538],[918.4303],[1041.6776],[1163.8529],[1286.9077],[1408.2551],[1530.3999],[1653.56],[1776.3412]])

```

**Comment by crucialfelix** [comment]
btw. I did test with just shift-enter on the line. It did work fine for me.

Can you check the console for errors and "toggle keybinding resolver" to make sure that your shortcut is matching ?

**Comment by tatecarson** [comment]
I forgot that that was in. If you just replace the nil with a value I still get the problem. Keybind toggle doesn't show any problems. The line will evaluate but anything below the line won't, and strangely anything above the line will.

**Comment by crucialfelix** [comment]
what do you mean "anything below the line won't" ?

If you position the cursor somewhere on a line then it will evaluate that line and that line only.

If you select the whole file and then evaluate then it should evaluate all that you have selected.

(I'm trying to state things in an overly obvious and clear way. if I sound like "stating the bleeding obvious" it's because I'm trying to ;)

**Comment by tatecarson** [comment]
`//example of eval problem

a  //i can evaluate this line

a = [[183.71933],[306.13547],[428.95813],[551.17237],[673.88556],[795.8538],[918.4303],[1041.6776],[1163.8529],[1286.9077],[1408.2551],[1530.3999],[1653.56],[1776.3412]] //and this one


a //but not this one `

**Comment by tatecarson** [comment]
//example of eval problem

a  //i can evaluate this line

a = [[183.71933],[306.13547],[428.95813],[551.17237],[673.88556],[795.8538],[918.4303],[1041.6776],[1163.8529],[1286.9077],[1408.2551],[1530.3999],[1653.56],[1776.3412]] //and this one


a //but not this one

**Comment by crucialfelix** [comment]
It's because soft-wrap is on.  I'll fix that.

**Comment by crucialfelix** [comment]
I was using buffer position is different than screen position. if softwrap is on then the screen line numbers are different than the buffer line numbers.

**Comment by crucialfelix** [comment]
btw. if you are using VIM mode then you may like this styling I did: https://medium.com/@crucialfelix/powerline-status-bar-and-cursor-styling-for-atom-vim-mode-7eab64491548#.gnbaipker

I just fixed it so that the eval-flash now happens correctly even if in vim-mode insert.

**Comment by crucialfelix** [comment]
my new mouse has a screwed up scroll wheel and it keeps jumping around. so I'm forced to use more key commands to navigate.

I use a limited number of basic vim commands. I'm no vim golfer.
