### ISSUE TITLE
Comments are only block style

### ISSUE THREAD

**Issue by woolgathering** [crucialfelix/atom-supercollider#78]
Cmd-/ only uses the block comment style, even on single lines. This only occurs when using the Supercollider syntax and not other syntaxes. I've tried editing grammars/supercollider.cson for a fix but I'm really just shooting in the dark.

I'd much prefer that the commenting behavior be the same as in other syntaxes, where all lines that are commented out are done as single lines unless otherwise specified. I imagine this is an easy fix, I just don't know where to look.

**Comment by crucialfelix** [comment]
I think it depends on which package you use for commenting.

https://atom.io/packages/search?q=comment

The grammar identifies what a comment looks like, and then the commenting package is what makes the editor do/undo it.  

Different packages have their own language support:

https://github.com/javaguirre/comment/blob/master/lib/comment.json
https://github.com/whoisthecoon/atom-block-comment-plus/blob/master/lib/languages.js

Supercollider should identify as a javascript for purposes of comments. I don't really know how to make it do that:

https://github.com/crucialfelix/atom-supercollider/blob/master/grammars/supercollider.cson

**Comment by crucialfelix** [comment]
It is definitely the comment package that determines this. Nothing I would want to do from inside atom-supercollider

This one promises to eventually support all languages:
https://atom.io/packages/multi-comment

**Comment by dyfer** [comment]
Hello,
I know this issue is closed, but is there really no solution to this? It would be very helpful to be able to use line comments. Thanks!

**Comment by woolgathering** [comment]
Fixed in my fork.

**Comment by crucialfelix** [comment]
I'm checking the solution from @woolgathering 

I was under the impression that it has nothing to do with the language file.
