### ISSUE TITLE
Help File Navigation

### ISSUE THREAD

**Issue by jamesopstad** [crucialfelix/atom-supercollider#80]
Thanks for your work on atom-supercollider. It works great. I'm just encountering one issue which is that when I load a help file the links within it won't work. It's therefore not possible to navigate the help system. I'm not sure if atom-supercollider or supercollider itself is the source of the problem. I have the same issue on OS X and Linux.

**Comment by crucialfelix** [comment]
When you open a help file you are starting up sclang and it opens the help file in its Qt gui.  No longer inside atom or atom-supercollider.

Can you navigate links if you open help files from the IDE ?  Is it really all links or just a few ?

**Comment by jamesopstad** [comment]
Some links work. I'm not able to predict which I'm afraid. In the IDE all links work.

**Comment by crucialfelix** [comment]
It isn't atom-supercollider that is opening the help files. Rather it is sclang running on the command line.

So you would have to file that bug with supercollider.  Something like:

### Links in help files are broken when sclang running on the command line versus sclang running inside the SC IDE.
- List exactly which links do not work.

At least let me know here which links do not work.

**Comment by jamesopstad** [comment]
Thanks. Turns out it's a known issue - [https://github.com/supercollider/supercollider/issues/2295](url)

**Comment by jamesopstad** [comment]
Thanks. Turns out it's a known issue - https://github.com/supercollider/supercollider/issues/2295
