### ISSUE TITLE
Deprecated selector in `supercollider/styles/supercollider.less`

### ISSUE THREAD

**Issue by filippoguida** [crucialfelix/atom-supercollider#82]
In `supercollider/styles/supercollider.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.post-window atom-text-editor::shadow` => `.post-window atom-text-editor.editor`

* `.post-window atom-text-editor::shadow.scroll-view` => `.post-window atom-text-editor.editor.scroll-view`

* `atom-text-editor::shadow .line,
atom-text-editor::shadow .line.cursor-line,
atom-text-editor.is-focused.insert-mode::shadow .line.cursor-line` => `atom-text-editor.editor .line,
atom-text-editor.editor .line.cursor-line,
atom-text-editor.is-focused.insert-mode.editor .line.cursor-line`

* `atom-text-editor::shadow .line.line-error,
atom-text-editor::shadow .line.cursor-line.line-error,
atom-text-editor.is-focused.insert-mode::shadow .line.cursor-line.line-error` => `atom-text-editor.editor .line.line-error,
atom-text-editor.editor .line.cursor-line.line-error,
atom-text-editor.is-focused.insert-mode.editor .line.cursor-line.line-error`

* `atom-text-editor::shadow .line.line-highlight,
atom-text-editor::shadow .line.cursor-line.line-highlight,
atom-text-editor.is-focused.insert-mode::shadow .line.cursor-line.line-highlight` => `atom-text-editor.editor .line.line-highlight,
atom-text-editor.editor .line.cursor-line.line-highlight,
atom-text-editor.is-focused.insert-mode.editor .line.cursor-line.line-highlight`

* `atom-text-editor::shadow .line.eval-flash,
atom-text-editor::shadow .line.cursor-line.eval-flash,
atom-text-editor.is-focused.insert-mode::shadow .line.cursor-line.eval-flash` => `atom-text-editor.editor .line.eval-flash,
atom-text-editor.editor .line.cursor-line.eval-flash,
atom-text-editor.is-focused.insert-mode.editor .line.cursor-line.eval-flash`

* `atom-text-editor::shadow .line.eval-success,
atom-text-editor::shadow .line.cursor-line.eval-success,
atom-text-editor.is-focused.insert-mode::shadow .line.cursor-line.eval-success` => `atom-text-editor.editor .line.eval-success,
atom-text-editor.editor .line.cursor-line.eval-success,
atom-text-editor.is-focused.insert-mode.editor .line.cursor-line.eval-success`

* `atom-text-editor::shadow .line.eval-error,
atom-text-editor::shadow .line.cursor-line.eval-error,
atom-text-editor.is-focused.insert-mode::shadow .line.cursor-line.eval-error,
atom-text-editor::shadow .line.eval-syntax-error,
atom-text-editor::shadow .line.cursor-line.eval-syntax-error,
atom-text-editor.is-focused.insert-mode::shadow .line.cursor-line.eval-syntax-error` => `atom-text-editor.editor .line.eval-error,
atom-text-editor.editor .line.cursor-line.eval-error,
atom-text-editor.is-focused.insert-mode.editor .line.cursor-line.eval-error,
atom-text-editor.editor .line.eval-syntax-error,
atom-text-editor.editor .line.cursor-line.eval-syntax-error,
atom-text-editor.is-focused.insert-mode.editor .line.cursor-line.eval-syntax-error`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by bagong** [comment]
It's still there, in 0.8 too. Sorry for being nitpicking @crucialfelix , it's a lovely package!

**Comment by crucialfelix** [comment]
Nit has been picked ! Thanks

**Comment by bagong** [comment]
Thank you!!! :smile:
