### ISSUE TITLE
Syntax highlighting Symbols

### ISSUE THREAD

**Issue by cechandler** [crucialfelix/atom-supercollider#94]
I've poked around in the grammars supercollider.cson file and see that symbols are listed there:

```
{
    'match': '\\\\[a-zA-Z0-9\\_]+'
    'name': 'entity.name.symbol.supercollider'
}
```

But they don't appear colored like other elements (e.g. classes, variables, comments, etc.). Is it possible to highlight them? Does this have to do with the syntax theme I am using (One Dark)? Thanks!

**Comment by crucialfelix** [comment]
Try swapping the theme first. Probably most generic languages don't differentiate between a string and a symbol so there aren't always definitions in themes. That's smalltalk and objective-c. Though actually JavaScript ES6 now has Symbol. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

**Comment by crucialfelix** [comment]
I will add notes about symbols and those custom themes to the docs. That's very useful.
