### ISSUE TITLE
SC Lib Compile error

### ISSUE THREAD

**Issue by KonVas** [crucialfelix/atom-supercollider#99]
The problem insists but sporadically, so there are no standard steps to reproduce. When I recompile I run some code but I get Library not compiled. After couple of times trying to recompile it works. Here is the post window:

`compiling class library...
...
	Found 714 primitives.
	Compiling directory '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/Extensions'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Vowel'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Dirt-Samples'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/SuperDirt'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Canvas3D'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/XML'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib'
	Compiling directory '/Users/konstantinos/.atom/packages/supercollider/node_modules/supercolliderjs/lib/supercollider-js'
ERROR: Class extension for nonexistent class 'Document'
     In file:'../../../../../../Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Lang/Workflow/extDocument-openStartup.sc'
ERROR: Class extension for nonexistent class 'Document'
     In file:'../../../../../../Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Lang/Workflow/extDocument-closeAllHelp.sc'
	numentries = 1412679 / 25812000 = 0.055
	7170 method selectors, 3600 classes
	method table size 24736448 bytes, big table size 206496000
	Number of Symbols 18024
	Byte Code Size 642528
	compiled 697 files in 8.85 seconds

Info: 8 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done

localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.02 seconds
compileError
`
Not entirely sure this is related: " Class extension for nonexistent class 'Document'"

**Comment by KonVas** [comment]
> Could you post some more messages from the console ?
I just managed to reproduced the problem, so evaluating the code returns this ->

compiling class library...
...
	Found 714 primitives.
	Compiling directory '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/Extensions'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Vowel'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Dirt-Samples'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/SuperDirt'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/Canvas3D'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/XML'
	Compiling directory '/Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib'
	Compiling directory '/Users/konstantinos/.atom/packages/supercollider/node_modules/supercolliderjs/lib/supercollider-js'
ERROR: Class extension for nonexistent class 'Document'
     In file:'../../../../../../Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Lang/Workflow/extDocument-openStartup.sc'
ERROR: Class extension for nonexistent class 'Document'
     In file:'../../../../../../Users/konstantinos/Library/Application Support/SuperCollider/downloaded-quarks/wslib/wslib-classes/Lang/Workflow/extDocument-closeAllHelp.sc'
	numentries = 1412679 / 25812000 = 0.055
	7170 method selectors, 3600 classes
	method table size 24736448 bytes, big table size 206496000
	Number of Symbols 18024
	Byte Code Size 642528
	compiled 697 files in 8.97 seconds

Info: 8 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done

localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.04 seconds
compileError


*** Welcome to SuperCollider 3.9.3. *** For help type cmd-d.
Library is not compiled
Library is not compiled
Library is not compiled

**Comment by crucialfelix** [comment]
OK, now I get it.

The problem is here I guess:

https://github.com/crucialfelix/supercolliderjs/blob/77a26c02cf1cdfe5b86699810ab46c6c315f975c/src/lang/internals/sclang-io.js#L146-L147

The reg-ex is not matching `*** Welcome to SuperCollider 3.9.3. *** For help type cmd-d.`

I will see when I can fix that. I hope soon.

**Comment by birv2** [comment]
Not sure if this goes here, and I realize this isn't a support forum, but I'd love to get Supercollider working and have spent hours chasing down dependencies, errors, etc. I'm at the point where I got the following errors and don't know if I need to install Quarks and if so, how, within Atom. Using Win10. 
![image](https://user-images.githubusercontent.com/8216770/71480919-a77b3200-27c9-11ea-8bc9-91a39917a6dd.png)
